#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacs'
export VISUAL='emacs'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export PROV_MAVEN_HOME=~/lookingglass/java/tools/apache-maven-2.2.1
export LVP_MAVEN_HOME=/Users/jhenrie/lookingglass/java/tools/apache-maven-3.0.4
export MAVEN_HOME=${LVP_MAVEN_HOME}
export JAVA_HOME=`/usr/libexec/java_home`
export ANT_HOME=/usr/bin/ant
export FLASH_PLAYER=/Applications/Flash\ Player.app/Contents/MacOS
export NETHACK_HOME=/usr/games/lib/nethackdir

# GO Environment setup
export CLOUD_GO_PATH=/Users/jhenrie/Documents/code/cloud/go-lmd-ws
export PERSONAL_GO_PATH=/Users/jhenrie/Documents/code/go-home
export PORTMON_GO_PATH=/Uusers/jhenrie/Documents/code/zabbix/go
export GOPATH=$CLOUD_GO_PATH
export GOBIN=$GOPATH/bin

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $MAVEN_HOME/bin
  $FLASH_PLAYER
  /Users/jhenrie/lookingglass/bin
  /bin
  /usr/{bin,sbin}
  /sbin
  /usr/games
  /usr/local/mysql/bin
  /opt/X11/bin
  /Applications/Server.app/Contents/ServerRoot/usr/{bin,sbin}
  /opt/ImageMagick/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Functions
#
goPersonal() {
  unset GOPATH
  unset GOBIN
  export GOPATH=$PERSONAL_GO_PATH
  export GOBIN=$GOPATH/bin
}

goCloud() {
  unset GOPATH
  unset GOBIN
  export GOPATH=$CLOUD_GO_PATH
  export GOBIN=$GOPATH/bin
}

goPortMon() {
  unset GOPATH
  unset GOBIN
  export GOPATH=$PORTMON_GO_PATH
  export GOBIN=$GOPATH/bin
}

#
# Alias
#
alias setJdk6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)'
alias setJdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
alias setJdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'

alias setCloudGo=goCloud
alias setPersonalGo=goPersonal
alias setPortmonGo=goPortMon

#
# WTF Module Environment Variables
#
export WTF_JIRA_API_KEY=gcCbDZMr22TlRCyfOyMnC51B